### ISSUE TITLE
How do I split a package over multiple libraries?

### ISSUE THREAD

**Issue by beruic** [madskristensen/Packman#22]
For example bootstrap comes with both CSS, JS and Fonts. I need to have them placed under the corresponding folders in an MVC 5 project.

**Comment by madskristensen** [comment]
Right now you can't. It is something I'm looking into, but so far I think only Bootstrap is relevant for this feature. 

Keep in mind the reason MVC 5 using `Scripts` and `Content` folders is because the NuGet packages used require those two folders. If you're not using NuGet you can now have folder called `lib` and put all the packman packages in there if you'd like.

**Comment by beruic** [comment]
That's exactly what I did. Add a `lib` folder.

However Bootstrap is not alone, as Font-awesome is relevant too, but I think a `lib` folder works better, so perhaps you should add a note about that to the documentation :)

**Comment by madskristensen** [comment]
Good idea. Thanks
